

language: python
python:
  - 2.7
script:
  - python helloworld.py

#setup appfog
before_deploy: "echo 'ready?'"
deploy:
  provider: appfog
  skip-cleanup: true
  email: puram.suresh@gmail.com
  password: travis123
  app: 
  master:app.html
after_deploy: "echo 'completed'"
