

language: python
python:
  - 2.7
script:
  - python helloworld.py

#setup appfog
before_deploy: "echo 'ready?'"
deploy:
  provider: appfog
  skip-cleanup: true
  api_key:
    secure: "eIlyFhQWuPwK3-Vbr_yYfg"
  app: 
  master:app.html

